modLoader = "kotlinforforge"
loaderVersion = "[4,)"
license = "MIT"

[[mods]]
modId = "cobblemon_forge_mdk"
version = "1.0.0"
displayName = "Cobblemon Forge Template Sidemod"
description = '''

'''

[[dependencies.cobblemon_forge_mdk]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1]"
ordering = "NONE"
side = "BOTH"

[[dependencies.cobblemon_forge_mdk]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.cobblemon_forge_mdk]]
modId = "cobblemon"
mandatory = true
versionRange = "[1.4.0,)"
ordering = "NONE"
side = "BOTH"
